    version: '3.8'

    services:
      frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        expose:
          - 8080
        environment:
          - NODE_ENV=production
        networks:
          - internal

    networks:
      internal:
    