    services:
      frontend:
        build: .
        networks:
          - internal
        environment:
          - VUE_APP_API_URL=http://backend:3001
        expose:
          - 8080

    networks:
      internal:
    