    server {
        listen 80;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            resolver 127.0.0.11 valid=30s ipv6=off;
            set $backend_upstream http://backend:3001;
            proxy_pass $backend_upstream/api/;
        }
    }
    